### ISSUE TITLE
compatibility with OCCT 7.8.0

### ISSUE THREAD

**Issue by francesco-ballarin** [NGSolve/netgen#170]
I am trying to build netgen against the recently released OCCT 7.8.0 and getting the following error
```
[ 59%] Building CXX object CMakeFiles/nglib.dir/libsrc/occ/Partition_Loop3d.cxx.o
/usr/local/bin/mpicxx -DHAVE_DLFCN_H -DMETIS -DNETGEN_PYTHON -DNG_MPI4PY -DNG_PYTHON -DOCCGEOMETRY -DPARALLEL -DPYBIND11_SIMPLE_GIL_MANAGEMENT -Dnglib_EXPORTS -I/tmp/netgen-src/build -I/tmp/netgen-src -I/tmp/netgen-src/include -I/tmp/netgen-src/libsrc -I/tmp/netgen-src/libsrc/include -I/tmp/netgen-src/external_dependencies/pybind11/include -I/usr/include/python3.11 -I/usr/local/lib/python3.11/site-packages/mpi4py/include/mpi4py -isystem /usr/local/include/opencascade -O2 -g -DNDEBUG -std=gnu++17 -fPIC -fvisibility=hidden -MD -MT CMakeFiles/nglib.dir/libsrc/occ/Partition_Loop3d.cxx.o -MF CMakeFiles/nglib.dir/libsrc/occ/Partition_Loop3d.cxx.o.d -o CMakeFiles/nglib.dir/libsrc/occ/Partition_Loop3d.cxx.o -c /tmp/netgen-src/libsrc/occ/Partition_Loop3d.cxx
In file included from /tmp/netgen-src/libsrc/occ/Partition_Loop3d.jxx:29,
                 from /tmp/netgen-src/libsrc/occ/Partition_Loop3d.ixx:10,
                 from /tmp/netgen-src/libsrc/occ/Partition_Loop3d.cxx:14:
/tmp/netgen-src/libsrc/occ/Partition_Loop3d.hxx:32:13: fatal error: TopTools_OrientedShapeMapHasher.hxx: No such file or directory
   32 |    #include <TopTools_OrientedShapeMapHasher.hxx>
```

The upstream offending commit seems to be https://github.com/Open-Cascade-SAS/OCCT/commit/1103eb60af84b32f44af1b1fc4222f32e4575daf

**Comment by francesco-ballarin** [comment]
Further errors I can get by running `make -k`

```
[  1%] Built target makerls
-- Found Git: /usr/bin/git (found version "2.40.1") 
[  1%] Built target ng_generate_version_file
[  8%] Built target ngcore
[ 10%] Built target pyngcore
[ 10%] Building CXX object CMakeFiles/nglib.dir/libsrc/occ/Partition_Spliter.cxx.o
[ 11%] Building CXX object CMakeFiles/nglib.dir/libsrc/occ/Partition_Loop3d.cxx.o
[ 11%] Building CXX object CMakeFiles/nglib.dir/libsrc/occ/occgeom.cpp.o
[ 11%] Building CXX object CMakeFiles/nglib.dir/libsrc/occ/occ_face.cpp.o
In file included from /tmp/shared-occ/netgen/libsrc/occ/Partition_Loop3d.jxx:29,
                 from /tmp/shared-occ/netgen/libsrc/occ/Partition_Loop3d.ixx:10,
                 from /tmp/shared-occ/netgen/libsrc/occ/Partition_Loop3d.cxx:14:
/tmp/shared-occ/netgen/libsrc/occ/Partition_Loop3d.hxx:32:13: fatal error: TopTools_OrientedShapeMapHasher.hxx: No such file or directory
   32 |    #include <TopTools_OrientedShapeMapHasher.hxx>
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /tmp/shared-occ/netgen/libsrc/occ/Partition_Spliter.cxx:36:
/tmp/shared-occ/netgen/libsrc/occ/Partition_Loop3d.hxx:32:13: fatal error: TopTools_OrientedShapeMapHasher.hxx: No such file or directory
   32 |    #include <TopTools_OrientedShapeMapHasher.hxx>
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/nglib.dir/build.make:1273: CMakeFiles/nglib.dir/libsrc/occ/Partition_Spliter.cxx.o] Error 1
make[2]: *** [CMakeFiles/nglib.dir/build.make:1259: CMakeFiles/nglib.dir/libsrc/occ/Partition_Loop3d.cxx.o] Error 1
[ 12%] Building CXX object CMakeFiles/nglib.dir/libsrc/occ/occ_vertex.cpp.o
[ 12%] Building CXX object CMakeFiles/nglib.dir/libsrc/occ/occ_edge.cpp.o
/tmp/shared-occ/netgen/libsrc/occ/occ_vertex.cpp: In member function 'virtual size_t netgen::OCCVertex::GetHash() const':
/tmp/shared-occ/netgen/libsrc/occ/occ_vertex.cpp:22:21: error: 'const class TopoDS_Vertex' has no member named 'HashCode'
   22 |       return vertex.HashCode(std::numeric_limits<Standard_Integer>::max());
      |                     ^~~~~~~~
/tmp/shared-occ/netgen/libsrc/occ/occ_edge.cpp: In member function 'virtual size_t netgen::OCCEdge::GetHash() const':
/tmp/shared-occ/netgen/libsrc/occ/occ_edge.cpp:58:19: error: 'const class TopoDS_Edge' has no member named 'HashCode'
   58 |       return edge.HashCode(std::numeric_limits<Standard_Integer>::max());
      |                   ^~~~~~~~
/tmp/shared-occ/netgen/libsrc/occ/occ_face.cpp: In member function 'virtual size_t netgen::OCCFace::GetHash() const':
/tmp/shared-occ/netgen/libsrc/occ/occ_face.cpp:35:19: error: 'const class TopoDS_Face' has no member named 'HashCode'
   35 |       return face.HashCode(std::numeric_limits<Standard_Integer>::max());
      |                   ^~~~~~~~
make[2]: *** [CMakeFiles/nglib.dir/build.make:1399: CMakeFiles/nglib.dir/libsrc/occ/occ_vertex.cpp.o] Error 1
make[2]: *** [CMakeFiles/nglib.dir/build.make:1385: CMakeFiles/nglib.dir/libsrc/occ/occ_edge.cpp.o] Error 1
In file included from /tmp/shared-occ/netgen/libsrc/occ/occgeom.cpp:13:
/tmp/shared-occ/netgen/libsrc/occ/occ_solid.hpp: In member function 'virtual size_t netgen::OCCSolid::GetHash() const':
/tmp/shared-occ/netgen/libsrc/occ/occ_solid.hpp:20:56: error: 'const class TopoDS_Solid' has no member named 'HashCode'
   20 |         size_t GetHash() const override { return solid.HashCode(std::numeric_limits<Standard_Integer>::max()); }
      |                                                        ^~~~~~~~
make[2]: *** [CMakeFiles/nglib.dir/build.make:1371: CMakeFiles/nglib.dir/libsrc/occ/occ_face.cpp.o] Error 1
/tmp/shared-occ/netgen/libsrc/occ/occgeom.cpp: In lambda function:
/tmp/shared-occ/netgen/libsrc/occ/occgeom.cpp:1719:29: error: 'const class TopoDS_Shape' has no member named 'HashCode'
 1719 |         auto occ_hash = key.HashCode(1<<31UL);
      |                             ^~~~~~~~
/tmp/shared-occ/netgen/libsrc/occ/occgeom.cpp:1720:44: error: template argument 1 is invalid
 1720 |         return std::hash<decltype(occ_hash)>()(occ_hash);
      |                                            ^
make[2]: *** [CMakeFiles/nglib.dir/build.make:1301: CMakeFiles/nglib.dir/libsrc/occ/occgeom.cpp.o] Error 1
make[2]: Target 'CMakeFiles/nglib.dir/build' not remade because of errors.
make[1]: *** [CMakeFiles/Makefile2:526: CMakeFiles/nglib.dir/all] Error 2
make[1]: Target 'all' not remade because of errors.
make: *** [Makefile:166: all] Error 2
make: Target 'default_target' not remade because of errors.
```

All of these errors are due to
https://github.com/Open-Cascade-SAS/OCCT/commit/1103eb60af84b32f44af1b1fc4222f32e4575daf

if @JSchoeberl @mhochsteger @ChrLackner you want to have a look, just be aware that you  must not use the `master` branch of https://github.com/Open-Cascade-SAS/OCCT/tree/master, use instead the 7.8.0 tag https://github.com/Open-Cascade-SAS/OCCT/releases/tag/V7_8_0
For whatever reason, the master branch of OCCT has fallen behind the tag. (thanks to Christophe Geuzaine for noticing that in https://gitlab.onelab.info/gmsh/gmsh/-/issues/2744)

**Comment by Neumann-A** [comment]
> Removed Hash Specialization Classes
> The majority of include files containing only specialized hashes have been removed. Their functionality has been consolidated into the hashed object include file (in the "std" namespace).
> It is guaranteed that each removed hash class has been transferred to the native hash mechanism of the hashed class.
> 
> The migration problem may arise at compile time. Ensure that you remove any files that have been deprecated.

So just remove the missing includes and call `std::hash`?

**Comment by Neumann-A** [comment]
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 0846f39bd..f7516afa4 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -372,25 +372,20 @@ if (USE_OCC)
       TKGeomAlgo
       TKGeomBase
       TKHLR
-      TKIGES
       TKLCAF
       TKMath
       TKMesh
       TKOffset
       TKPrim
-      TKSTEP
-      TKSTEP209
-      TKSTEPAttr
-      TKSTEPBase
-      TKSTL
+      TKDESTL
       TKService
       TKShHealing
       TKTopAlgo
       TKV3d
       TKVCAF
       TKXCAF
-      TKXDEIGES
-      TKXDESTEP
+      TKDEIGES
+      TKDESTEP
       TKXSBase
       TKernel
     )
diff --git a/libsrc/occ/Partition_Loop3d.hxx b/libsrc/occ/Partition_Loop3d.hxx
index e1716691c..e8a434911 100644
--- a/libsrc/occ/Partition_Loop3d.hxx
+++ b/libsrc/occ/Partition_Loop3d.hxx
@@ -10,27 +10,16 @@
 #ifndef _Partition_Loop3d_HeaderFile
 #define _Partition_Loop3d_HeaderFile
 
-#ifndef _TopTools_ListOfShape_HeaderFile
-#include <TopTools_ListOfShape.hxx>
-#endif
-#ifndef _TopTools_IndexedDataMapOfShapeListOfShape_HeaderFile
-#include <TopTools_IndexedDataMapOfShapeListOfShape.hxx>
-#endif
-#ifndef _Standard_Boolean_HeaderFile
+#include <Standard_Version.hxx>
 #include <Standard_Boolean.hxx>
-#endif
-#ifndef _Standard_Real_HeaderFile
 #include <Standard_Real.hxx>
-#endif
-#ifndef _Standard_Version_HeaderFile
-#include <Standard_Version.hxx>
-#endif
+#include <TopTools_ListOfShape.hxx>
+#include <TopTools_IndexedDataMapOfShapeListOfShape.hxx>
 
-#if OCC_VERSION_HEX < 0x070000
+#if OCC_VERSION_HEX < 0x070000 || OCC_VERSION_HEX > 0x070799
 #else
    #include <TopTools_ShapeMapHasher.hxx>
    #include <TopTools_OrientedShapeMapHasher.hxx>
-   #include <TopTools_MapOfOrientedShape.hxx>
 #endif
 
 class TopoDS_Shape;
@@ -38,6 +27,8 @@ class TopoDS_Shape;
 #if OCC_VERSION_HEX < 0x070000
    class TopTools_ListOfShape;
    class TopTools_MapOfOrientedShape;
+#else
+#include <TopTools_MapOfOrientedShape.hxx>
 #endif
 
 class TopoDS_Edge;
diff --git a/libsrc/occ/occ_edge.cpp b/libsrc/occ/occ_edge.cpp
index 0c907d78b..fd64c9a42 100644
--- a/libsrc/occ/occ_edge.cpp
+++ b/libsrc/occ/occ_edge.cpp
@@ -55,7 +55,11 @@ namespace netgen
 
     size_t OCCEdge::GetHash() const
     {
+#if OCC_VERSION_HEX < 0x070800
       return edge.HashCode(std::numeric_limits<Standard_Integer>::max());
+#else
+      return std::hash<TopoDS_Shape>{}(edge); 
+#endif
     }
 
     void OCCEdge::ProjectPoint(Point<3>& p, EdgePointGeomInfo* gi) const
diff --git a/libsrc/occ/occ_face.cpp b/libsrc/occ/occ_face.cpp
index 239982aa8..ea4dd15b4 100644
--- a/libsrc/occ/occ_face.cpp
+++ b/libsrc/occ/occ_face.cpp
@@ -32,7 +32,11 @@ namespace netgen
 
     size_t OCCFace::GetHash() const
     {
+#if OCC_VERSION_HEX < 0x070800
       return face.HashCode(std::numeric_limits<Standard_Integer>::max());
+#else
+      return std::hash<TopoDS_Shape>{}(face); 
+#endif
     }
 
     Point<3> OCCFace::GetCenter() const
diff --git a/libsrc/occ/occ_solid.hpp b/libsrc/occ/occ_solid.hpp
index d598de4a2..66f28d73a 100644
--- a/libsrc/occ/occ_solid.hpp
+++ b/libsrc/occ/occ_solid.hpp
@@ -16,8 +16,11 @@ namespace netgen
         OCCSolid(TopoDS_Shape dshape)
             : solid(TopoDS::Solid(dshape))
         { }
-
+#if OCC_VERSION_HEX < 0x070800
         size_t GetHash() const override { return solid.HashCode(std::numeric_limits<Standard_Integer>::max()); }
+#else
+        size_t GetHash() const override { return std::hash<TopoDS_Solid>{}(solid); }
+#endif
     };
 }
 
diff --git a/libsrc/occ/occ_vertex.cpp b/libsrc/occ/occ_vertex.cpp
index 6e83c8944..be8e38732 100644
--- a/libsrc/occ/occ_vertex.cpp
+++ b/libsrc/occ/occ_vertex.cpp
@@ -19,6 +19,10 @@ namespace netgen
 
     size_t OCCVertex::GetHash() const
     {
+#if OCC_VERSION_HEX < 0x070800
       return vertex.HashCode(std::numeric_limits<Standard_Integer>::max());
+#else
+      return std::hash<TopoDS_Shape>{}(vertex); 
+#endif
     }
 }
diff --git a/libsrc/occ/occgeom.cpp b/libsrc/occ/occgeom.cpp
index bc0383f99..826134ba0 100644
--- a/libsrc/occ/occgeom.cpp
+++ b/libsrc/occ/occgeom.cpp
@@ -1716,8 +1716,12 @@ namespace netgen
 
     // enumerate shapes and archive only integers
     auto my_hash = [](const TopoDS_Shape & key) {
+#if OCC_VERSION_HEX < 0x070800
         auto occ_hash = key.HashCode(1<<31UL);
         return std::hash<decltype(occ_hash)>()(occ_hash);
+#else
+        return std::hash<TopoDS_Shape>{}(key);
+#endif
     };
     TopTools_IndexedMapOfShape shape_map;
     Array<TopoDS_Shape> shape_list;

```

**Comment by mhochsteger** [comment]
Thanks for the suggestions! Turns out, we don't need the hash functions anymore at all.

Fixed with commit 486c7d9bcb950dfb33c2a59b68eca3e720af4107

**Comment by francesco-ballarin** [comment]
Thanks @mhochsteger , but unfortunately that doesn't fix the issue as I originally reported it.

Tried compiling `netgen` again, and I still get

```
[ 59%] Building CXX object CMakeFiles/nglib.dir/libsrc/occ/Partition_Spliter.cxx.o
/usr/local/bin/mpicxx -DHAVE_DLFCN_H -DMETIS -DNETGEN_PYTHON -DNG_MPI4PY -DNG_PYTHON -DOCCGEOMETRY -DPARALLEL -DPYBIND11_SIMPLE_GIL_MANAGEMENT -Dnglib_EXPORTS -I/tmp/netgen-src/build -I/tmp/netgen-src -I/tmp/netgen-src/include -I/tmp/netgen-src/libsrc -I/tmp/netgen-src/libsrc/include -I/tmp/netgen-src/external_dependencies/pybind11/include -I/usr/include/python3.10 -I/usr/local/lib/python3.10/dist-packages/mpi4py/include/mpi4py -isystem /usr/local/include/opencascade -O2 -g -DNDEBUG -std=gnu++17 -fPIC -fvisibility=hidden -MD -MT CMakeFiles/nglib.dir/libsrc/occ/Partition_Spliter.cxx.o -MF CMakeFiles/nglib.dir/libsrc/occ/Partition_Spliter.cxx.o.d -o CMakeFiles/nglib.dir/libsrc/occ/Partition_Spliter.cxx.o -c /tmp/netgen-src/libsrc/occ/Partition_Spliter.cxx
In file included from /tmp/netgen-src/libsrc/occ/Partition_Loop3d.jxx:29,
                 from /tmp/netgen-src/libsrc/occ/Partition_Loop3d.ixx:10,
                 from /tmp/netgen-src/libsrc/occ/Partition_Loop3d.cxx:14:
/tmp/netgen-src/libsrc/occ/Partition_Loop3d.hxx:32:13: fatal error: TopTools_OrientedShapeMapHasher.hxx: No such file or directory
   32 |    #include <TopTools_OrientedShapeMapHasher.hxx>
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/nglib.dir/build.make:1259: CMakeFiles/nglib.dir/libsrc/occ/Partition_Loop3d.cxx.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /tmp/netgen-src/libsrc/occ/Partition_Spliter.cxx:36:
/tmp/netgen-src/libsrc/occ/Partition_Loop3d.hxx:32:13: fatal error: TopTools_OrientedShapeMapHasher.hxx: No such file or directory
   32 |    #include <TopTools_OrientedShapeMapHasher.hxx>
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
which probably isn't surprising, considering that the commit you linked does not change that file (but the diff by @Neumann-A did)

Once you have a follow up fix please let me know and I will test it.
